blackducksoftware/blackduck-common

src/main/java/com/blackducksoftware/integration/hub/CIEnvironmentVariables.java, src/main/java/com/blackducksoftware/integration/hub/HubIntRestService.java, src/main/java/com/blackducksoftware/integration/hub/HubSupportHelper.java, src/main/java/com/blackducksoftware/integration/hub/capabilities/HubCapabilitiesEnum.java, src/main/java/com/blackducksoftware/integration/hub/cli/CLILocation.java, src/main/java/com/blackducksoftware/integration/hub/item/HubItem.java, src/main/java/com/blackducksoftware/integration/hub/item/HubItems.java, src/main/java/com/blackducksoftware/integration/hub/item/HubItemsService.java, src/main/java/com/blackducksoftware/integration/hub/policy/api/PolicyRule.java, src/main/java/com/blackducksoftware/integration/hub/policy/api/PolicyRuleConditionFieldEnum.java, src/main/java/com/blackducksoftware/integration/hub/rest/RestConnection.java, src/test/java/com/blackducksoftware/integration/hub/HubSupportHelperTest.java, src/test/java/com/blackducksoftware/integration/hub/cli/CLILocationTest.java, src/test/java/com/blackducksoftware/integration/hub/item/HubItemTest.java, src/test/java/com/blackducksoftware/integration/hub/policy/api/PolicyRuleTest.java
Changes to implement http Post methods in Rest Connection
This is to allow the maven plugin to be able to upload the common BOM file format.
Updated the hub support helper to use an enum for capabilities of the Hub. 
Convert the create methods in HubIntRestService to use the post methods in RestConnection.
=> Ps rest connection post

src/main/java/com/blackducksoftware/integration/hub/HubIntRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/notification/NotificationRestService.java, src/main/java/com/blackducksoftware/integration/hub/rest/CredentialsRestConnection.java, src/main/java/com/blackducksoftware/integration/hub/rest/RestConnection.java, src/test/java/com/blackducksoftware/integration/hub/cli/CLILocationTest.java, src/test/java/com/blackducksoftware/integration/hub/polling/HubEventPollingTest.java, src/test/java/com/blackducksoftware/integration/hub/report/api/RiskReportGeneratorTest.java
Make the Rest Connection class abstract in order to remove the need for
a HubServerConfig object to be populated correctly to create the rest
connection.  Create a CredentialsRestConnection that will take the
HubServerConfig object in the constructor and initialize the
RestConnection object. If the username and password are empty then do
not call the setCookies method in the constructor.
=> Make Rest Connection abstract and add a CredentialsRestConnection

src/main/java/com/blackducksoftware/integration/hub/rest/CredentialsRestConnection.java, src/main/java/com/blackducksoftware/integration/hub/rest/RestConnection.java, src/test/java/com/blackducksoftware/integration/hub/rest/RestConnectionTest.java
RestConnection:
1. Use getParameters().set() rather than add(), in case timeout is changed after being set.
2. Call setTimeout() from constructor, in case user doesn't set timeout (adding this will change the default behavior from infinite timeout to default timeout).
3. New constructor that takes a logger
=> Sb rest connection handle request hang

src/main/java/com/blackducksoftware/integration/hub/api/item/MetaService.java, src/main/java/com/blackducksoftware/integration/hub/api/notification/VulnerabilityNotificationContent.java, src/main/java/com/blackducksoftware/integration/hub/api/project/AffectedProjectVersion.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/extension/ExtensionConfigDataService.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/NotificationDataService.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/NotificationResults.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/item/NotificationContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/item/PolicyContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/item/PolicyOverrideContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/item/PolicyViolationClearedContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/item/PolicyViolationContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/item/ProjectVersion.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/item/VulnerabilityContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/transformer/AbstractPolicyTransformer.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/transformer/PolicyViolationClearedTransformer.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/transformer/PolicyViolationOverrideTransformer.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/transformer/PolicyViolationTransformer.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/transformer/VulnerabilityTransformer.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/parallel/ParallelResourceProcessor.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/parallel/ParallelResourceProcessorResults.java, src/test/java/com/blackducksoftware/integration/hub/notification/processor/EventTestUtil.java
Separated out ProjectVersion (dataservice layer) from AffectedProjectVersion (api layer).
Fixed NPE in MetaService
ParallelResourceProcessor.process() now returns an object that includes a list of exceptions caught. Similar change to notification service get*Notifications().
=> Sb separate affected project version from project version

src/main/groovy/com/blackducksoftware/integration/hub/dataservice/notification/transformer/PolicyViolationTransformer.java
If components violating policy are cleared or overridden the policy
violation event is never generated and it is skipped.  This causes a
problem where you don't have matching policy violation event and policy
override or clear events that cancel each other out in a time range.
This can result in reporting incorrect information.  To fix this remove
the checks
=> Fix the transformer to create the policy violation event to add

build.gradle, src/main/java/com/blackducksoftware/integration/hub/api/view/PolicyOverrideNotificationView.java, src/main/java/com/blackducksoftware/integration/hub/api/view/ReducedNotificationView.java, src/main/java/com/blackducksoftware/integration/hub/api/view/RuleViolationClearedNotificationView.java, src/main/java/com/blackducksoftware/integration/hub/api/view/VulnerabilityNotificationView.java, src/main/java/com/blackducksoftware/integration/hub/notification/AbstractNotificationTransformer.java, src/main/java/com/blackducksoftware/integration/hub/notification/AbstractPolicyTransformer.java, src/main/java/com/blackducksoftware/integration/hub/notification/PolicyViolationClearedTransformer.java, src/main/java/com/blackducksoftware/integration/hub/notification/PolicyViolationOverrideTransformer.java, src/main/java/com/blackducksoftware/integration/hub/notification/PolicyViolationTransformer.java, src/main/java/com/blackducksoftware/integration/hub/notification/VulnerabilityTransformer.java, src/main/java/com/blackducksoftware/integration/hub/service/ComponentService.java, src/main/java/com/blackducksoftware/integration/hub/service/NotificationService.java, src/test/groovy/com/blackducksoftware/integration/hub/api/recipe/BdioUploadRecipeTest.java, src/test/groovy/com/blackducksoftware/integration/hub/api/recipe/CheckPolicyForProjectVersionRecipeTest.groovy, src/test/groovy/com/blackducksoftware/integration/hub/api/recipe/ComponentManagementRecipeTest.java
The NotificationView had a content member and the sub-classes also have
a content field that causes a problem for gson.  Create a new class
ReducedNotificationView that does not contain a content member in order
for gson to deserialize into the correct types.
=> Changes to handle notification processing of the content field.

src/main/java/com/blackducksoftware/integration/hub/cli/parallel/ScanPathCallable.java, src/main/java/com/blackducksoftware/integration/hub/cli/summary/ScanTargetOutput.java, src/main/java/com/blackducksoftware/integration/hub/service/SignatureScannerService.java
We used to clean some of the files on success, this is to delete all of the files in the log directory and the directory itself when the scan is successful and is configured for cleanup
=> Handling the deletion of the log directory

build.gradle, src/main/java/com/synopsys/integration/blackduck/signaturescanner/command/ScanPathsUtility.java, src/test/groovy/com/synopsys/integration/blackduck/signaturescanner/ScanPathsTest.java
Executing Signature Scanner from Blackduck Hub currently fails on
Alpine Linux environments as the Oracle JRE packaged with Signature
Scanner requires glibc, which is not present on Alpine Linux. They use
musl libc instead.
Executing Signature Scanner with the systems default OpenJDK JRE is not
possible as hub-common uses the Oracle JDK packaged with Signature
Scanner.
Starting Signature Scanner from command line works, as it considers the
environment variable BDS_JAVA_HOME and takes the JRE located there
instead of the Oracle JRE pacakged with Signature Scanner.
Unit tests are done with PowerMock instead of a wrapper class for
java.lang.System so the constructor of ScanPathsUtility stays the same
as it is used by hub-detect and as such changing it would cause
incompatibility. We had to …
=> Consider BDS_JAVA_HOME for Signature Scanner Execution

src/main/java/com/synopsys/integration/blackduck/signaturescanner/command/ScanPathsUtility.java, src/test/groovy/com/synopsys/integration/blackduck/signaturescanner/ScanPathsTest.java
When BDS_JAVA_HOME was set, its value was used as the java executable
path. By convention any JAVA_HOME variable usually points to the
installation directory of the JVM though, e.g.
/usr/lib/jvm/java-8-openjdk-amd64/jre. Hence, to determine the path to
the java executable correctly, we need to append /bin/java or
/bin/java.exe
Fixes #224
=> Fix Java Executable Path for Signature Scanner

src/main/java/com/synopsys/integration/blackduck/service/ProjectService.java
Problem:  Calls to `ProjectService::getComponentsWithMatchedFilesForProjectVersion` and `ProjectService::getMatchedFiles` will return `VersionBomComponentModel` objects having no `matchedFiles`.
In my debugging tests, in `getAllResponses` the call to `hubService.getAllResponses` correctly retrieves a list of `MatchedFileView`, but the function will return an empty list if `getAllResponses` returned a non-empty list, otherwise it will return… also an empty list.
I could not test the modified code because I cannot build the project (my local proxy prevents me for downloading the dependencies).
=> Fix: matched files not properly retrieved.

src/main/java/com/synopsys/integration/blackduck/service/ComponentService.java, src/test/groovy/com/synopsys/integration/blackduck/api/ComponentServiceTestIT.java
For components like Cycler 0.10.0, the library fails to find an exact component match when the origin id returned from Black Duck is a different case than the one searched for. 
Example:
Searched for "cycler/0.10.0"
Received "Cycler/0.10.0"
=> fix(ComponentService) Fixed ComponentService::getExactComponentMatchnot matching against origin id's of different cases.

src/main/java/com/synopsys/integration/blackduck/rest/ApiTokenBlackDuckHttpClient.java
I added the Content-Length header as part of the API Token authentication. It was pointed out in https://github.com/blackducksoftware/blackduck-common/issues/268 that this is best practice in a POST request. See the GitHub issue for more details.
=> Adding the Content-Length header

src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatch.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatchBuilder.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommand.java
Adding field individualFileMatching to ScanCommand to reflect new parameter in BD CLI
https://jira-sig.internal.synopsys.com/browse/IDETECT-1860
=> Add individual file matches to scan command

build.gradle, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommand.java, src/test/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommandTest.java
This is a potential solution for issues faced by the current implementation for parsing a string of scan cli arguments.
Outsourcing parsing to org.apache.tools.ant.types.Commandline.
Added a test to ScanCommandTest to assure edge cases that we were previously vulnerable to are now handled (input on what other edge cases may be missed by the test/what other behavior we'd wish to verify would be appreciated).
=> Utilize library class to parse command string into list of arguments.

build.gradle, src/main/java/com/synopsys/integration/blackduck/service/dataservice/LicenseService.java, src/test/java/com/synopsys/integration/blackduck/service/dataservice/LicenseDataServiceTestIT.java, src/test/java/com/synopsys/integration/blackduck/service/dataservice/ProjectServiceTestIT.java
Also made getLicenseUrlByLicenseName return an Optional instead of throwing an exception on a miss.
=> Provide API for getting suggested license names for a given query token.

src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2FileUploadService.java, src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2RetryAwareStreamUploader.java, src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2UploadJob.java, src/main/java/com/synopsys/integration/blackduck/service/BlackDuckServicesFactory.java, src/test/java/com/synopsys/integration/blackduck/bdio2/Bdio2RetryAwareStreamUploaderTest.java, src/test/java/com/synopsys/integration/blackduck/bdio2/Bdio2UploadJobTest.java
Retry IP bdio upload if it fails. (Earlier changes didn't account for the fact that an exception is thrown when there's a failure. With these changes it'll handle the exception case, or the no-exception case, in case integration-rest is changed in the future to not throw exceptions on failure.)
=> Sb retry bdio upload

src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2FileUploadService.java, src/main/java/com/synopsys/integration/blackduck/codelocation/CodeLocationWaiter.java, src/test/java/com/synopsys/integration/blackduck/bdio2/Bdio2UploadJobTest.java, src/test/java/com/synopsys/integration/blackduck/comprehensive/CreateProjectWithBdioAndVerifyBOMTest.java, src/test/java/com/synopsys/integration/blackduck/comprehensive/InstallAndRunSignatureScannerTestIT.java, src/test/java/com/synopsys/integration/blackduck/comprehensive/recipe/BdioUploadRecipeTest.java
Needed to use the new poll tracker and constructor for the config class.
=> IDETECT-3475 | fix to accommodate changes made to the polling mechanism introduced by the separation of the config from the polling | jppetrakis

src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatch.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatchBuilder.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ReducedPersistence.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommand.java, src/test/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommandTest.java
Adds flags to allow users to specify if unmatched files should be persisted or purged when running signature scans. This aligns with new features in BlackDuck 2022.10
=> add reduced persistence flags for signature scans

src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2FileUploadService.java, src/main/java/com/synopsys/integration/blackduck/service/BlackDuckApiClient.java, src/main/java/com/synopsys/integration/blackduck/version/BlackDuckVersion.java, src/test/java/com/synopsys/integration/blackduck/version/BlackDuckVersionTest.java
This work moves the version class files from the main detect code to this library. This allows us to have version checks at various levels of the code which more use cases are deeming necessary.
The version checks in this PR are then used to determine if we can safely omit the HTTP headers for project names and project versions as BD will pick up these values from the BDIO header instead. This fixes cases where non-ASCII characters were previously supplied in the HTTP headers causing REST calls to fail.
Note: this only conditionally adds REST headers for uploading intelligent persistent related BDIO files. It does not alter all areas where REST headers are used.
=> version check for http headers

build.gradle, src/main/java/com/synopsys/integration/blackduck/service/BlackDuckApiClient.java, src/test/java/com/synopsys/integration/blackduck/service/BlackDuckApiClientTestIT.java, src/test/java/com/synopsys/integration/blackduck/service/dataservice/ProjectServiceTestIT.java
Newer generations of blackduck-common-api have moved us to using v6 endpoints. This appears to be a problem when PUTting projects. 
What's happening is that we send an Accept header of application/vnd.blackducksoftware.project-detail-6+json which seems to trigger different code than sending an Accept header of application/vnd.blackducksoftware.project-detail-5+json. The BlackDuck team has informed us that when triggering the v6 code they require a Content-Type header (or else we get 406 errors claiming they don't know what media type our data is in). 
What I'm doing here is sending the media type associated with the endpoint in the PUT request, just like what we do with the Accept header. This works well for the use cases I've been testing but would be interested in thoughts.
=> Need to send content type header when issuing PUTs to newer endpoints

src/main/java/com/synopsys/integration/blackduck/service/BlackDuckApiClient.java
The current calls to BlackDuck hide some of the information that callers need to determine what to do next. For example, they do not return the headers from a call when it is not a successful call. This prevents Detect from intelligently retrying calls since the Retry-After header is missing.
This is a simple fix to return the raw response from BlackDuck to callers.
=> Return additional REST response information

build.gradle, src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2FileUploadService.java, src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2RetryAwareStreamUploader.java, src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2StreamUploader.java, src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2UploadJob.java, src/main/java/com/synopsys/integration/blackduck/codelocation/intelligentpersistence/IntelligentPersistenceBatchRunner.java, src/main/java/com/synopsys/integration/blackduck/codelocation/intelligentpersistence/IntelligentPersistenceCallable.java, src/main/java/com/synopsys/integration/blackduck/codelocation/intelligentpersistence/IntelligentPersistenceCodeLocationCreationRequest.java, src/main/java/com/synopsys/integration/blackduck/codelocation/intelligentpersistence/IntelligentPersistenceService.java, src/test/java/com/synopsys/integration/blackduck/bdio2/Bdio2RetryAwareStreamUploaderTest.java, src/test/java/com/synopsys/integration/blackduck/bdio2/Bdio2UploadJobTest.java, src/test/java/com/synopsys/integration/blackduck/comprehensive/recipe/IntelligentPersistenceRecipeTest.java
When BlackDuck returns a 429 we should look for the retry-after header and wait that number of seconds before resubmitting the scan.
=> Enhance retry mechanism for scan starts when BlackDuck specifies retry-after header

build.gradle, src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2RetryAwareStreamUploader.java
This does some improvements to blackduck-common to make it work with more BlackDuck server
1) It rolls back to the 2023.4.2.2 generation as that works with all supported servers for most use cases. The 2023.10 generation was breaking with earlier versions of BlackDuck
2) It updates a retry message to make it more easy to understand why it is retrying. It also shows the message at the debug level which is more consistent with other messages of this type.
=> revert to 2023.4.2.2 api and enhance retry error message

src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2RetryAwareStreamUploader.java, src/test/java/com/synopsys/integration/blackduck/bdio2/Bdio2RetryAwareStreamUploaderTest.java
We want to only retry on 429 codes if we get a retry-after header and that header contains a value larger than 0. In other words, only retry when BlackDuck specifically tells us how long to wait. Other retryable codes should continue to use the previous Fibonacci backoff approach used by the resilient framework.
=> do not retry if we get a 429 with no or zero retry after header

src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommand.java, src/test/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommandTest.java
Fix for system property key-value pairs being delimited by space instead of the equals character.
A recent change caused proxy details to be specifies as `-Dkey value` instead of `-Dkey=value`.
This turned out to be an invalid way to specify these properties which cause them to be rejected by java.
=> Fix for system property key-value pairs being delimited by space instead of the equals character

src/main/java/com/synopsys/integration/blackduck/service/dataservice/RoleService.java, src/main/java/com/synopsys/integration/blackduck/service/dataservice/UserGroupService.java, src/test/java/com/synopsys/integration/blackduck/service/dataservice/UserServiceTestIT.java
Add method for fetching server-only roles assigned to user.
This will allow detect to log this limited set of roles instead of what it does currently, which is fetch potentially thousands of project-specific roles.
This will be used by Detect as part of the following change: https://github.com/blackducksoftware/synopsys-detect/pull/1144
=> Add method for fetching server-only roles assigned to user

src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatch.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatchBuilder.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommand.java
This allows for passing a csv archive option to the signature scanner so that csv files can be created. Detect will begin doing this in offline mode so that users have access to the files.
=> Add csv archive support to signature scan invocation

src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ApiScannerInstaller.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ToolsApiScannerInstaller.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ZipApiScannerInstaller.java
For simplicity sake, just using one text file: blackDuckVersion.txt regardless of which API was used to download the scanner. 
This is the same version file as we have always used, so as far as the Detect output files are concerned, all is the same regardless of which API was used under the hood .
IDETECT-4434
=> Using a single version file regardless of API used for download.

src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ToolsApiScannerInstaller.java
IDETECT-4450 & IDETECT-4244
Updates ToolsApiScannerInstaller so we update the cacerts inside the scan-cli zip with each call to download the scanner (whether or not it was updated).
=> fix (ToolsApiScannerInstaller): Update scan-cli trust store with each scan run

README.md, src/test/java/com/synopsys/integration/blackduck/comprehensive/NotificationsTestIT.java, src/test/java/com/synopsys/integration/blackduck/http/client/IntHttpClientTestHelper.java, src/test/java/com/synopsys/integration/blackduck/http/client/TestingPropertyKey.java
Fixes an intermittently failing IT: IDETECT-4473
Please see ticket comment for details but in summary: Project/project version creations followed immediately by a deletion leads to a race condition. Other notification types appear to come from Hub backend and I did not see any APIs this test case could call on to trigger one of the other available types of notifications. The DELETE has been moved to the end of the test case as a clean up. Only one version is created instead of two because even after notifications are delivered and asserted, a race condition still happened when cleaning up.
=> Changes related to refactoring and fixing ITs.

src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/command/BlackDuckOnlineProperties.java, src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/command/ScanCommand.java, src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/command/SnippetMatching.java, src/test/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/ScanBatchBuilderTest.java, src/test/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/command/ScanCommandTest.java
Removing some options for signature scans that were deprecated in Detect 9 along with their corresponding usages and tests.
=> Remove full snippet matching and full snippet only matching for signature scans

src/test/java/com/blackduck/integration/blackduck/service/BlackDuckApiClientTestIT.java
Since we are using lower version of bd-common-api, this change would fix the failing test which was updated for 2023.10.0.5 release. Do not have much context on the cause of failure but this was how this test was fixed last time.
=> Fix Test Failure

build.gradle
Pending release pipeline, brings in https://github.com/blackducksoftware/blackduck-common-api/pull/64
Due to IDETECT-4497, we are using release/v2023.4.2.7.x in bd-common-api as the base branch for IDETECT-4262.
=> Bump bd-common-api version to 2023.4.2.8

src/main/java/com/blackduck/integration/blackduck/phonehome/BlackDuckPhoneHomeHelper.java, src/main/java/com/blackduck/integration/blackduck/service/dataservice/BlackDuckRegistrationService.java
**JIRA Ticket:**
IDETECT-4209
**Description:**
This merge request addresses the issue of excessive warning logs generated when non-admin users attempt to fetch the registration ID on the endpoint `/api/registration`. 
~The solution involves using a `ThreadLocal` variable to manage the state of whether the `getRegistrationId()` method has been called before or not by a non-syadmin user. This ensures that repeated attempts to fetch the registration ID are avoided, thereby significantly reducing unnecessary warning logs.~
**Update 1:**
`BlackDuckRegistrationService` has been refactored. Now, it follows an eager approach. `getBlackDuckServerData()` method has been overloaded to accept `isAdmin` boolean flag. ~The passed boolean `isAdmin` flag is stored in a static local variable.
Before …
=> Reduce excessive logs when non-admin users fetch registration ID

build.gradle, src/main/java/com/blackduck/integration/blackduck/service/model/ProjectSyncModel.java, src/test/java/com/blackduck/integration/blackduck/service/model/ProjectSyncModelTest.java
To create and clone a project version at the same time, an update metadata field will be required to pass in the Project  Version creation request. Setting of that metadata takes place in bd-common.
Ticket: IDETECT-4671
=> Update Project Version Request to include update metadata

build.gradle
Brings in a new version of blackduck-common-api and its libraries to remove a vulnerability in Apache BeanUtils
=> rev blackduck-common-api

src/main/java/com/blackduck/integration/blackduck/service/dataservice/ComponentService.java
The request construction accidentally uses the path to the `version` view, instead of to the `component` view. So, in case the given search result matches a `component`, but not a `version`, the result is empty. Fix that by using the right variable.
=> ComponentService: Fix-up obtaining a component view for a search result

src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/ScanBatch.java, src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/ScanBatchBuilder.java, src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/command/ScanCommand.java
This new option allows for calling the signature scanner in SCASS mode. This will result in SCASS laying down the BDIO on disk so that it can be uploaded by other utilities, like Detect, instead of sending the BDIO itself to hub directly. This is for online mode. Offline mode will still happen as before.
=> Invoke signature scanner in SCASS mode

src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/command/ToolsApiScannerInstaller.java, src/test/java/com/blackduck/integration/blackduck/comprehensive/ToolsApiScannerInstallerTestIT.java
This PR fixes a bug where we do not want to use the new endpoints for HUB versions 2025.4.0 or below. To achieve that, we will check the HUB version on detect side and then pass the architecture based on the result. Essentially, we do not want to pass `arm64` in case where HUB is below required version.
=> Pass OS architecture from Detect

src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/command/ApiScannerInstaller.java, src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/command/ScanCliMetadata.java, src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/command/ScanPathsUtility.java, src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/command/ToolsApiScannerInstaller.java, src/test/java/com/blackduck/integration/blackduck/comprehensive/ToolsApiScannerInstallerTestIT.java
This PR takes in a new metadata.json file which is packaged with new scan cli. This will handle the case when arm64 users will try to upgrade from 10.6.0 to 10.7.0 version of Detect and have locally cached scan cli. Currently there is no way for Detect to differentiate the architecture between old and new scan cli for us to be able to update the locally stored scan cli.
There are new conditions when fresh download will get triggered, if the metadata file does not exist and if it exists the current osArchitecture value is not equal to the one stored in file and also checks if the os value is different from the expected one.
=> Add support for new metadata.json file in new scan-cli

src/test/java/com/blackduck/integration/blackduck/comprehensive/ToolsApiScannerInstallerTestIT.java
Remove this test for now since our builds are still running on older versions of HUB and there is no way to get version value in here.
=> Remove Test for Architecture check
