blackducksoftware/blackduck-common

src/main/java/com/blackducksoftware/integration/hub/encryption/EncryptionUtils.java, src/main/java/com/blackducksoftware/integration/hub/encryption/PasswordDecrypter.java, src/main/java/com/blackducksoftware/integration/hub/encryption/PasswordEncrypter.java, src/test/java/com/blackducksoftware/integration/hub/encryption/PasswordDecrypterTest.java, src/test/java/com/blackducksoftware/integration/hub/encryption/PasswordEncrypterTest.java
Have the class throw the EncryptionException instead.
=> Changes to remove the need for IntLogger

src/main/java/com/blackducksoftware/integration/hub/ScannerSplitStream.java, src/test/java/com/blackducksoftware/integration/hub/ScannerSplitStreamTest.java, src/test/java/com/blackducksoftware/integration/hub/util/TestLogger.java, src/test/java/com/blackducksoftware/integration/hub/util/TestOutputStream.java
@akamen @jrichardBD @psantos1113 @stevebillings 
These changes are a little more involved than simply updating the test, so I wanted to have them reviewed. It might be appropriate to have a sit-down code review here to make sure that I've correctly addressed all the important edge cases.
=> Ekerwin updating test for windows

src/main/java/com/blackducksoftware/integration/hub/HubSupportHelper.java, src/main/java/com/blackducksoftware/integration/hub/ScanExecutor.java
--password option if the Hub is 3.1.0 or newer
=> IHCIC-45 Updating the password handling, so that we do not add the

src/main/java/com/blackducksoftware/integration/hub/item/HubItem.java, src/main/java/com/blackducksoftware/integration/hub/item/HubItemsService.java, src/main/java/com/blackducksoftware/integration/hub/policy/api/PolicyRule.java, src/test/java/com/blackducksoftware/integration/hub/policy/api/PolicyRuleTest.java
@ekerwin @akamen @stevebillings @psantos1113  Please review this PR
=> Getting policy rules

src/main/java/com/blackducksoftware/integration/hub/component/api/BomComponentVersionPolicyStatus.java, src/main/java/com/blackducksoftware/integration/hub/component/api/ComponentVersion.java, src/main/java/com/blackducksoftware/integration/hub/component/api/ComponentVersionStatus.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/NotificationItem.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/NotificationType.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/PolicyOverrideNotificationContent.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/PolicyOverrideNotificationItem.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/RuleViolationNotificationContent.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/RuleViolationNotificationItem.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/VulnerabilityNotificationContent.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/VulnerabilityNotificationItem.java, src/main/java/com/blackducksoftware/integration/hub/project/api/ProjectVersion.java, src/main/java/com/blackducksoftware/integration/hub/rest/RestConnection.java
includes the notifications api objects used by the hub-jira project.  Also includes a fix to the post method of RestConnection
=> Ps email notifier

src/main/java/com/blackducksoftware/integration/hub/component/api/ComponentVersion.java, src/main/java/com/blackducksoftware/integration/hub/notification/NotificationDateRange.java, src/main/java/com/blackducksoftware/integration/hub/notification/NotificationService.java, src/main/java/com/blackducksoftware/integration/hub/notification/NotificationServiceException.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/PolicyOverrideNotificationContent.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/PolicyOverrideNotificationItem.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/VulnerabilityNotificationContent.java, src/main/java/com/blackducksoftware/integration/hub/notification/api/VulnerabilitySourceQualifiedId.java, src/main/java/com/blackducksoftware/integration/hub/project/api/ProjectVersion.java, src/test/java/com/blackducksoftware/integration/hub/notification/NotificationServiceTest.java
=> 37: Added NotificationService and model classes

pom.xml, src/main/java/com/blackducksoftware/integration/hub/api/ComponentVersionRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/HubRequest.java, src/main/java/com/blackducksoftware/integration/hub/api/HubRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/NotificationRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/PolicyRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/ProjectRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/ProjectVersionRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/VersionBomPolicyRestService.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/AbstractDataService.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/NotificationDataService.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/items/NotificationContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/items/PolicyOverrideContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/items/PolicyViolationContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/items/VulnerabilityContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/transforms/AbstractNotificationTransform.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/transforms/AbstractPolicyTransform.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/transforms/PolicyViolationOverrideTransform.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/transforms/PolicyViolationTransform.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/transforms/VulnerabilityTransform.java, src/main/java/com/blackducksoftware/integration/hub/exception/HubItemTransformException.java, src/main/java/com/blackducksoftware/integration/hub/rest/RestConnection.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/items/PolicyOverrideItemTest.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/items/PolicyViolationItemTest.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/items/VulnerabilityItemTest.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/transforms/PolicyOverrideTransformTest.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/transforms/PolicyViolationTransformTest.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/transforms/VulnerabilityTransformTest.java
Changes to provide a dataservice to process notification items from the hub into usable objects.
=> Ps notification service refactor

src/main/java/com/blackducksoftware/integration/hub/api/project/ProjectVersion.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/items/NotificationContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/items/PolicyOverrideContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/items/PolicyViolationContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/items/VulnerabilityContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/transforms/AbstractPolicyTransform.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/transforms/PolicyViolationOverrideTransform.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/transforms/PolicyViolationTransform.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/transforms/VulnerabilityTransform.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/items/PolicyOverrideItemTest.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/items/PolicyViolationItemTest.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/items/VulnerabilityItemTest.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/transforms/PolicyOverrideTransformTest.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/transforms/PolicyViolationTransformTest.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/transforms/VulnerabilityTransformTest.java
Please review these changes to the Hub-Common transforms
=> Notification update information

src/main/java/com/blackducksoftware/integration/hub/rest/RestConnection.java
Fixing customer issues with java.lang.ClassCastException: org.restlet.data.Header cannot be cast to org.restlet.engine.header.Header
=> Fixing restlet header casting

src/main/java/com/blackducksoftware/integration/hub/api/NotificationRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/notification/RuleViolationClearedNotificationContent.java, src/main/java/com/blackducksoftware/integration/hub/api/notification/RuleViolationClearedNotificationItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/notification/NotificationDataService.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/notification/items/PolicyViolationClearedContentItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/notification/transforms/PolicyViolationClearedTransform.java, src/main/java/com/blackducksoftware/integration/hub/rest/RestConnection.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/notifications/items/RuleViolationClearedItemTest.java
Changes to support the policy violation cleared notification
=> Ps rule violation cleared notification

src/main/java/com/blackducksoftware/integration/hub/api/HubItemRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/HubRequest.java, src/main/java/com/blackducksoftware/integration/hub/api/extension/ExtensionConfigRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/extension/ExtensionItem.java, src/main/java/com/blackducksoftware/integration/hub/api/extension/ExtensionRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/extension/ExtensionUserOptionRestService.java, src/main/java/com/blackducksoftware/integration/hub/api/extension/UserOptionLinkItem.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/DataServicesFactory.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/extension/ExtensionConfigDataService.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/extension/transformer/UserConfigTransform.java, src/main/java/com/blackducksoftware/integration/hub/dataservices/parallel/ParallelResourceProcessor.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/extension/transformer/UserConfigTransformTest.java, src/test/java/com/blackducksoftware/integration/hub/dataservices/parallel/ParallelResourceProcessorTest.java, src/test/java/com/blackducksoftware/integration/hub/extension/api/ExtensionItemTest.java, src/test/java/com/blackducksoftware/integration/hub/extension/api/UserOptionLinkItemTest.java
@ekerwin please take a look.  Changes to use extension url rather than extension ID.
=> Additional extension services

src/main/java/com/blackducksoftware/integration/hub/rest/CredentialsRestConnection.java, src/main/java/com/blackducksoftware/integration/hub/rest/RestConnection.java
IHCIC-76 Adding the connect method. Users of RestConnection will have to call connect now.
=> Adding RestConnection connect

pom.xml, src/main/java/com/blackducksoftware/integration/hub/builder/HubCredentialsBuilder.java, src/main/java/com/blackducksoftware/integration/hub/builder/HubProxyInfoBuilder.java, src/main/java/com/blackducksoftware/integration/hub/builder/HubScanConfigBuilder.java, src/main/java/com/blackducksoftware/integration/hub/builder/HubServerConfigBuilder.java, src/main/java/com/blackducksoftware/integration/hub/validator/HubCredentialsValidator.java, src/main/java/com/blackducksoftware/integration/hub/validator/HubProxyValidator.java, src/main/java/com/blackducksoftware/integration/hub/validator/HubScanConfigValidator.java, src/main/java/com/blackducksoftware/integration/hub/validator/HubServerConfigValidator.java, src/test/java/com/blackducksoftware/integration/hub/global/HubCredentialsBuilderTest.java, src/test/java/com/blackducksoftware/integration/hub/global/HubProxyInfoBuilderTest.java, src/test/java/com/blackducksoftware/integration/hub/global/HubServerConfigBuilderTest.java
Changes to use the new Validators along with the builders to separate the work.
=> Validator implementation

src/main/java/com/blackducksoftware/integration/hub/api/notification/PolicyOverrideNotificationContent.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/NotificationDataService.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/transformer/AbstractNotificationTransformer.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/transformer/AbstractPolicyTransformer.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/transformer/PolicyViolationClearedTransformer.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/transformer/PolicyViolationOverrideTransformer.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/notification/transformer/PolicyViolationTransformer.java
Policy Violation: Exclude components that are not in violation
Policy Override: Exclude components that are not in violation-overridden. Get Policies from the right location. 
Policy Cleared: Only include rules matching the given set.
=> NotificationDataService bug fixes

pom.xml
Update hub common response latest build
=> Update hub common response latest build

pom.xml, src/main/groovy/com/blackducksoftware/integration/hub/api/project/ProjectRequestService.java, src/main/groovy/com/blackducksoftware/integration/hub/certificate/HubCertificateHandler.java, src/main/groovy/com/blackducksoftware/integration/hub/cli/CLILocation.java, src/main/groovy/com/blackducksoftware/integration/hub/cli/SimpleScanService.java, src/main/groovy/com/blackducksoftware/integration/hub/dataservice/cli/CLIDataService.groovy
This will auto insert the certificate, if appropriate, in to the cli's jre.
Also, some changes are here to support using a previously installed "offline" scan cli.
=> cli improvements

pom.xml, src/main/groovy/com/blackducksoftware/integration/hub/dataservice/cli/CLIDataService.groovy, src/main/groovy/com/blackducksoftware/integration/hub/dataservice/scan/ScanStatusDataService.java
Added code to the CLIDataService to ensure the status files are cleaned
up from the working directory.  Also added a convenience method to check
the status of the ScanSummaries by providing a ProjectVersionView
=> Enhancements to scanning to cleanup and check the status of a scan

pom.xml, src/main/groovy/com/blackducksoftware/integration/hub/service/HubResponseService.java
Added methods to retrieve the Hub response based on MediaType
=> Added methods to retrieve the Hub response based on MediaType

pom.xml, src/main/java/com/blackducksoftware/integration/hub/dataservice/phonehome/PhoneHomeDataService.java, src/main/java/com/blackducksoftware/integration/hub/dataservice/phonehome/PhoneHomeResponse.java
The response from starting phone home is now self-ending as it wraps the Future<Boolean>.
=> Alter phone home

src/main/java/com/blackducksoftware/integration/hub/service/UserGroupService.java
Added methods to get the inherited roles as well as, methods to encapsulate all of the roles, (directly assigned and inherited) into a single list.
=> Add methods to get inherited roles for the user groups

src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatch.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatchBuilder.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommand.java
Adding flag to ScanCommand that when set on Detect command line will pass scan CLI property onto the scanner
=> Added boolean field licenseSearch to ScanCommand

src/main/java/com/synopsys/integration/blackduck/configuration/BlackDuckServerConfig.java, src/main/java/com/synopsys/integration/blackduck/configuration/BlackDuckServerConfigBuilder.java, src/main/java/com/synopsys/integration/blackduck/service/BlackDuckService.java, src/main/java/com/synopsys/integration/blackduck/service/BlackDuckServicesFactory.java, src/test/java/com/synopsys/integration/blackduck/comprehensive/ComprehensiveCookbookTestIT.java, src/test/java/com/synopsys/integration/blackduck/comprehensive/recipe/BasicRecipe.java, src/test/java/com/synopsys/integration/blackduck/http/client/BlackDuckHttpClientTestIT.java, src/test/java/com/synopsys/integration/blackduck/http/client/IntHttpClientTestHelper.java, src/test/java/com/synopsys/integration/blackduck/http/transform/BlackDuckResponsesTransformerTestIT.java, src/test/java/com/synopsys/integration/blackduck/service/BlackDuckServiceTest.java
Note: Majority of edits were done by the IDE.
=> Update to use HttpUrl vs UrlSupport which was removed

src/main/java/com/synopsys/integration/blackduck/service/BlackDuckService.java, src/main/java/com/synopsys/integration/blackduck/service/dataservice/CodeLocationService.java, src/test/java/com/synopsys/integration/blackduck/comprehensive/CreateProjectWithBdioAndVerifyBOMTest.java, src/test/java/com/synopsys/integration/blackduck/service/dataservice/CodeLocationServiceTestIT.java
Also add pre/post clean up for CreateProjectWithBdioAndVerifyBOMTest
=> Add test for CodeLocationServiceTest.getCodeLocationByName

build.gradle, src/main/java/com/synopsys/integration/blackduck/service/model/BomComponent.java, src/main/java/com/synopsys/integration/blackduck/service/model/pdf/RiskReportPdfWriter.java
IDETECT-2376
[synopsys_detect_7_0_0_SIGQA18_SNAPSHOT_BlackDuck_RiskReport.pdf](https://github.com/blackducksoftware/blackduck-common/files/6416179/synopsys_detect_7_0_0_SIGQA18_SNAPSHOT_BlackDuck_RiskReport.pdf)
Example of what changes look like.
=> Add critical column to table in risk report pdf.

src/main/java/com/synopsys/integration/blackduck/service/dataservice/PolicyRuleService.java, src/main/java/com/synopsys/integration/blackduck/service/model/PolicyRuleExpressionSetBuilder.java, src/test/java/com/synopsys/integration/blackduck/service/dataservice/PolicyRuleServiceTestIT.java
Updating the policy searching by name to use a paged approach, fixing an issue with the PolicyRuleExpressionSetBuilder, adding a test for the policy search.
=> Updating the policy searching by name to use a paged approach

src/main/java/com/synopsys/integration/blackduck/bdio2/Bdio2RetryAwareStreamUploader.java, src/test/java/com/synopsys/integration/blackduck/bdio2/Bdio2RetryAwareStreamUploaderTest.java
There are some nuances to this we don't yet fully understand, so I anticipate this is going to present a troubleshooting challenge. I added some trace logging that will help if/when that day comes. While I was in there I realized I'd left some code paths / scenarios untested, so I added tests for those.
=> Sb retry logging and tests

src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatch.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatchBuilder.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommand.java, src/test/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommandTest.java
Adds a new flag to determine if a signature scan is a rapid one or not
=> Add rapid parameter

build.gradle
=> commit for cascaded version bump

src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatch.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/ScanBatchBuilder.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/BlackDuckOnlineProperties.java, src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScanCommand.java
Ad the option to set correlation ID for a signature scanner run.
=> correlation ID signature scanner option

build.gradle
common to consume 2023.1.0 bd-common-api
=> update version of common-api used and passed forward

build.gradle
Manually increment version as the pipeline failed to do this.
As the next step and long-term fix the pipeline failure should be better understood and the pipeline should be fixed.
=> Manually increment version as the pipeline failed to do this

src/test/java/com/synopsys/integration/blackduck/comprehensive/InstallAndRunSignatureScannerTestIT.java
Will be investigated and fixed post CF
=> Disable a failing IT for investigation post Cf

build.gradle
To release new version of bd-common compatible with Detect, this PR just updates the new released version of bd-common-api to be consumed in by Detect.
=> Update bd-common-api version

src/main/java/com/blackduck/integration/blackduck/codelocation/signaturescanner/command/ScanCommand.java
Add csv option conditionally based on if we are in online or offline mode.
=> add online csv mode

src/test/java/com/blackduck/integration/blackduck/service/BlackDuckApiClientTestIT.java
Fix Media Type test failing on build pipeline: https://build-sca.tools.duckutil.net/job/integration-builds-v2/job/generated-builds/job/libraries/job/blackduck-common/job/comprehensive/1959/
=> Fix Media Type Test

src/test/java/com/blackduck/integration/blackduck/comprehensive/ToolsApiScannerInstallerTestIT.java
Fix regression introduced in 2025.4.0: during test setup, decrementing major version caused test to fail because since scan-cli version has been decoupled from Hub version, the major version is 0 instead of 2023.. 2024.. etc.
Closes IDETECT-4708
=> Fix test case regression introduced in 2025.4.0
